//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cirnix.Global.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cirnix.Global.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 |cffff0000[|r |cff646464  |cff646eff|r |cff288C28 http://Cheatmap.tistory.com |r |cffffa500vA|r |cffff0000]|r
        ///|r*|r |cffFFB1BCThanks to used |cffFFFA78Getting Cheat Maps Welcome! |r|r*
        ///|cff288C28@선택|r - |cffffA500선택|r |cff646464 영웅/유닛 치트 적용자를 선택합니다.|r
        ///|cffCD0000Cafe Address|r |cffEE84EA
        ///|cff646eff이 방은|r |cffffbe0a3초 후|r|cff646eff에 저절로 |cffffbe0a폭파|r|cff646eff됩니다.|r |cffff0000(취소따윈 못합니다. 이미 늦었어!)|r
        ///|r |cff2c952c이(가)|r |cffffbe0a선택|r|cff2c952c되었습니다.|r
        ///|cffCD0000자동으로 리플레이가|r |cffEE84EA삭제 됩니다|r |cff6482FF
        ///|cfff [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string CheatSetPhrase {
            get {
                return ResourceManager.GetString("CheatSetPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        public static byte[] Cirnix {
            get {
                object obj = ResourceManager.GetObject("Cirnix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon CirnixIcon {
            get {
                object obj = ResourceManager.GetObject("CirnixIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        public static byte[] max {
            get {
                object obj = ResourceManager.GetObject("max", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
